platform :ios, '10.0'
use_frameworks!

target 'Faberbabel_Example' do
  pod 'Faberbabel', :path => '../'
  pod 'SwiftLint', '~> 0.39'

  target 'Faberbabel_Tests' do
    inherit! :search_paths
  end

  target 'Widget' do
    inherit! :search_paths
  end
end
