desc "Run all unit tests"
lane :tests do
  scan(
    workspace: "Example/Faberbabel.xcworkspace",
    configuration: "Debug",
    scheme: "Faberbabel-Example",
    clean: true,
    devices: ["iPhone 8"]
  )
end

desc "Linting"
lane :lint do
  swiftlint(
      mode: :lint,
      strict: true,
      executable: "Example/Pods/SwiftLint/swiftlint",
      path: "Example"
  )
end

desc "CI Check"
lane :ci_check do
  tests
  lint
  pod_lib_lint(
    use_bundle_exec: true,
    allow_warnings: false
  )
end